use_frameworks!
platform :ios, '9.0'

target 'ONOChat_Example' do
  pod 'ONOChat', :path => '../'
  pod 'AFNetworking'
  pod 'MJRefresh'

  target 'ONOChat_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
