// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Message;
@class UserData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProtocolRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProtocolRoot : GPBRootObject
@end

#pragma mark - UserData

typedef GPB_ENUM(UserData_FieldNumber) {
  UserData_FieldNumber_Uid = 1,
  UserData_FieldNumber_Name = 2,
  UserData_FieldNumber_Icon = 3,
  UserData_FieldNumber_Sign = 4,
  UserData_FieldNumber_Email = 5,
  UserData_FieldNumber_Birth = 6,
  UserData_FieldNumber_Mobile = 7,
  UserData_FieldNumber_Gender = 8,
  UserData_FieldNumber_Ex = 9,
};

/**
 * 有推送 用户信息
 **/
@interface UserData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *birth;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 用户性别，0表示未知，1表示男，2女表示女，其它会报参数错误 */
@property(nonatomic, readwrite) int32_t gender;

/** 用户名片扩展字段，最大长度1024字符，用户可自行扩展，建议封装成JSON字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ex;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_Uid = 1,
  Message_FieldNumber_Mid = 2,
  Message_FieldNumber_From = 3,
  Message_FieldNumber_To = 4,
  Message_FieldNumber_Type = 5,
  Message_FieldNumber_Content = 6,
  Message_FieldNumber_Tag = 7,
  Message_FieldNumber_Time = 8,
  Message_FieldNumber_Unread = 9,
};

@interface Message : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@property(nonatomic, readwrite) double time;

@property(nonatomic, readwrite) int32_t unread;

@end

#pragma mark - ErrorResponse

typedef GPB_ENUM(ErrorResponse_FieldNumber) {
  ErrorResponse_FieldNumber_Code = 1,
  ErrorResponse_FieldNumber_Message = 2,
  ErrorResponse_FieldNumber_Extra = 3,
};

@interface ErrorResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

#pragma mark - UserKick

typedef GPB_ENUM(UserKick_FieldNumber) {
  UserKick_FieldNumber_Content = 1,
};

/**
 * 推送 重复登录被提出
 **/
@interface UserKick : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - UserLoginRequest

typedef GPB_ENUM(UserLoginRequest_FieldNumber) {
  UserLoginRequest_FieldNumber_Token = 1,
};

/**
 * 请求 登陆接口
 **/
@interface UserLoginRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - UserLoginResponse

typedef GPB_ENUM(UserLoginResponse_FieldNumber) {
  UserLoginResponse_FieldNumber_User = 1,
  UserLoginResponse_FieldNumber_MessagesArray = 2,
};

/**
 * 响应 登陆
 **/
@interface UserLoginResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserData *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

#pragma mark - ReadMessageRequest

typedef GPB_ENUM(ReadMessageRequest_FieldNumber) {
  ReadMessageRequest_FieldNumber_Mid = 1,
};

/**
 * 请求 标记消息已读
 **/
@interface ReadMessageRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

@end

#pragma mark - SendMessageRequest

typedef GPB_ENUM(SendMessageRequest_FieldNumber) {
  SendMessageRequest_FieldNumber_Type = 1,
  SendMessageRequest_FieldNumber_To = 2,
  SendMessageRequest_FieldNumber_Content = 3,
  SendMessageRequest_FieldNumber_Tag = 4,
};

/**
 * 请求 发送消息
 **/
@interface SendMessageRequest : GPBMessage

/** 1文字 2图片 3表情 */
@property(nonatomic, readwrite) int32_t type;

/** 接收者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
